### ISSUE TITLE
5 | (Opcional) Crear perfil del usuario

### ISSUE THREAD

**Issue by MaxiCarrillo** [Sofi231098/grupo_13_moffy#51]
## Descripción
Se debe crear el archivo userProfile.ejs con todos los recursos necesarios, estilos CSS e imágenes en caso de ser necesarias.

## Requerimientos

- La página debe ser responsive, aplicar la teoría de Mobile First.
- La página debe tener un buen nivel de semántica.
- La página debe tener un buen nivel de accesibilidad.
- La página debe mostrar los datos del usuario que este en sesión en ese momento y además incluir la imagen de perfil.
- La página debe contar con un botón para la modificación de los datos del usuario.
- La página solo debe poder ser accedida si el usuario ha iniciado sesión (Aplicar authMiddleware).

**Comment by Sofi231098** [comment]
Me falta la edicion de los datos del usuario
